# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: "Build Example eyelash_sofle nrf display custom config"
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["eyelash_sofle_left", "eyelash_sofle_right"]'
      custom_config: '["#define MIRYOKU_KLUDGE_SOFT_OFF"]'
      kconfig: '["CONFIG_ZMK_PM_SOFT_OFF=y\nCONFIG_ZMK_POINTING=y\nCONFIG_ZMK_SLEEP=y\nCONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1600000\nCONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y\nCONFIG_ZMK_BLE_PASSKEY_ENTRY=y"]'
      modules: '["a741725193/zmk-sofle/main"]'